[package]
name = "test-prioritization"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
foldhash = "0.2"
html2text = "0.16"
indexmap = "2.12.1"
itertools = "0.14.0"
